name: cockroachdb-broker

releases:
- name: generic-odb-adapter
  version: latest
- name: on-demand-service-broker
  version: "0.16.1"
  url: git+https://github.com/pivotal-cf/on-demand-service-broker-release

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-90000
  update_watch_time: 1000-90000

instance_groups:
- name: broker
  azs: [z1]
  instances: 1
  jobs:
  - name: fake-cf
    release: generic-odb-adapter
    properties: {}

  - name: generic-odb-adapter
    release: generic-odb-adapter
    properties:
      service_instance_manifest: ((si_manifest))
      service_binding_manifest: ((sb_manifest))
      director:
        host: ((director_ip))
        cert: ((director_ssl))
        client: ((director_client))
        client_secret: ((director_client_secret))

  - name: broker
    release: on-demand-service-broker
    properties:
      disable_ssl_cert_verification: false
      port: 8080
      username: cockroachdb-broker
      password: ((broker_password))
      bosh:
        url: https://((director_ip)):25555
        root_ca_cert: ((director_ssl.ca))
        authentication:
          uaa:
            url: https://((director_ip)):8443 # todo
            client_id: ((director_client))
            client_secret: ((director_client_secret))
      cf: # todo
        root_ca_cert: ((uaa_ssl_ca))
        url: http://localhost:8081 # todo
        authentication:
          url: https://((director_ip)):8443
          client_credentials:
            client_id: ((director_client))
            secret: ((director_client_secret))
      service_catalog:
        bindable: true
        id: 97e8336e-172c-4bf8-8574-96fbbd3d0f58
        service_name: cockroachdb
        service_description: Dedicated CockroachDB
        plan_updatable: true
        tags: [database]
        plans:
        - plan_id: bcfb07be-4559-48b2-ac10-ca490f7324cd
          name: default
          description: "Default"
          instance_groups:
          - name: unused
            instances: 1
            azs: [unused]
            networks: [unused]
            persistent_disk_type: unused
            vm_type: unused
            vm_extensions: [unused]
      service_deployment:
        releases:
        - jobs: [unused]
          name: unused
          version: unused
        stemcell:
          os: unused
          version: unused

  networks:
  - name: default
  stemcell: default
  vm_type: default

- name: upgrade-all-service-instances
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: upgrade-all-service-instances
    release: on-demand-service-broker
  networks:
  - name: default
  stemcell: default
  vm_type: default

variables:
- name: broker_password
  type: password
