name: # set by broker

releases:
- name: cockroachdb
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3445.2"

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-120000
  update_watch_time: 5000-120000

instance_groups:
- name: cockroachdb
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: cockroachdb
    release: cockroachdb
    provides:
      conn: {shared: true}
    properties:
      cert: ((server_cert))
  - name: cockroachdb-database
    release: cockroachdb
    provides:
      database: {shared: true}
    properties:
      name: ((database))
  - name: cockroachdb-user
    release: cockroachdb
    provides:
      root_user: {shared: true}
    properties:
      cert: ((user_root_cert))
  vm_type: default
  stemcell: default
  persistent_disk: 32_768
  networks:
  - name: default

variables:
- name: ca
  type: certificate
  options:
    is_ca: true
    common_name: cockroachdb
- name: server_cert
  type: certificate
  options:
    ca: ca
    common_name: node
    alternative_names: ["*.cockroachdb.default.((si_deployment_name_dns_friendly)).bosh"] # todo let director do it
    extended_key_usage:
    - server_auth
    - client_auth
- name: user_root_cert
  type: certificate
  options:
    ca: ca
    common_name: root
    extended_key_usage:
    - client_auth
- name: database
  type: password
