name: ((broker_name))

releases:
- name: bosh-generic-sb
  version: latest
- name: bpm
  version: 0.1.0
  url: git+https://github.com/cloudfoundry-incubator/bpm-release

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-90000
  update_watch_time: 1000-90000

instance_groups:
- name: broker
  azs: [z1]
  instances: 1
  jobs:
  - name: bosh-generic-sb
    release: bosh-generic-sb
    properties:
      http:
        password: ((broker_password))
      director:
        host: ((director_ip))
        cert: ((director_ssl))
        client: ((director_client))
        client_secret: ((director_client_secret))
      services:
      - id: ((srv_id))
        name: ((srv_name))
        description: ((srv_description))
        plans:
        - id: default
          name: default
          description: default
          si_manifest: ((si_manifest))
          si_params: ((si_params))
          sb_manifest: ((sb_manifest))
          sb_params: ((sb_params))

  networks:
  - name: default
  stemcell: default
  vm_type: default

variables:
- name: broker_password
  type: password

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm
    properties: {}
